# Default values for validator.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 3
image:
  repository: sudermanjr/validator-nu-kubernetes
  tag: latest
  pullPolicy: Always
service:
  name: validator
  type: ClusterIP
  externalPort: 8888
  internalPort: 8888
ingress:
  enabled: true
  hosts:
    - validator
  annotations:
    kubernetes.io/ingress.class: nginx
